import { Content, Inter } from 'next/font/google'
import './globals.module.css'
import NavBar from '@/componentes/NavBar/NavBar'
import Context from '@/Context/Context'
import Footer from '@/componentes/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
        <Context>{children}</Context>
      <Footer />
      </body>
    </html>
  )
}
